use std::process::Command;

use eggbau::{egg, export, mm0};

const CONVERSION_FIXTURE: &str = "tests/fixtures/stage4_conversion.mm0";

#[test]
fn script_emit_outputs_environment_only_script() {
    let output = eggbau::cli::run(["eggbau", "script", "emit", CONVERSION_FIXTURE]).unwrap();

    assert!(output.contains(";; generated by eggbau 0.1.0\n"));
    assert!(output.contains(&format!(";; input: {CONVERSION_FIXTURE}\n")));
    assert!(output.contains(";; script kind: environment\n"));
    assert!(output.contains("(ruleset saturation)"));
    assert!(output.contains(":name \"f_id\""));
    assert!(!output.contains(";; theorem: target\n"));
    assert!(!output.contains("(prove (= (F EggbauVarTargetX) EggbauVarTargetX))"));
}

#[test]
fn script_emit_outputs_theorem_proof_problem_script() {
    let output = eggbau::cli::run([
        "eggbau",
        "script",
        "emit",
        CONVERSION_FIXTURE,
        "--theorem",
        "target",
    ])
    .unwrap();

    assert!(output.contains(";; generated by eggbau 0.1.0\n"));
    assert!(output.contains(";; theorem: target\n"));
    assert!(output.contains(";; script kind: proof-problem\n"));
    assert!(output.contains(";; theorem-local symbolic inputs\n"));
    assert!(output.contains("(constructor EggbauVarTargetX () S)"));
    assert!(output.contains("(run-schedule (repeat 1024"));
    assert!(output.contains("(prove (= (F (EggbauVarTargetX)) (EggbauVarTargetX)))"));
}

#[test]
fn theorem_script_matches_the_main_prove_program() {
    let input = std::fs::read_to_string(CONVERSION_FIXTURE).unwrap();
    let env = mm0::parse_env(&input).unwrap();
    let export_env = export::ExportEnv::from_mm0(&env).unwrap();
    let proof = egg::prove_theorem(&env, &export_env, "target").unwrap();

    let output = eggbau::cli::run([
        "eggbau",
        "script",
        "emit",
        CONVERSION_FIXTURE,
        "--theorem",
        "target",
    ])
    .unwrap();

    assert_eq!(output, proof.egglog_program);
}

#[test]
fn script_emit_scheduled_is_available_under_script_namespace() {
    let output = eggbau::cli::run([
        "eggbau",
        "script",
        "emit",
        CONVERSION_FIXTURE,
        "--scheduled",
    ])
    .unwrap();

    assert!(output.contains("(run-schedule (saturate (run saturation)))"));
}

#[test]
fn old_emit_egglog_top_level_command_is_rejected() {
    let output = Command::new(env!("CARGO_BIN_EXE_eggbau"))
        .arg("emit-egglog")
        .output()
        .unwrap();

    assert!(!output.status.success());
    assert!(
        String::from_utf8(output.stderr)
            .unwrap()
            .contains("unsupported command: emit-egglog")
    );
}
