use std::process::Command;

use eggbau::export::{
    ConversionDirection, ExportEnv, ExportTermKind, render_egglog, render_egglog_with_schedule,
};
use eggbau::mm0::{SaturationMode, parse_env};

const CONVERSION_INPUT: &str = r#"
sort s;
provable sort wff;
term z: s;
term f (x: s): s;
term eq (x y: s): wff;
--| @relation s eq eq_refl eq_trans eq_sym _
axiom eq_refl (x: s): $ eq x x $;
axiom eq_trans (x y z: s): $ eq x y $ > $ eq y z $ > $ eq x z $;
axiom eq_sym (x y: s): $ eq x y $ > $ eq y x $;
--| @saturation ltr
axiom f_id (x: s): $ eq (f x) x $;
"#;

const HORN_INPUT: &str = r#"
sort s;
provable sort wff;
term z: s;
term eq (x y: s): wff;
term p (x: s): wff;
term q (x: s): wff;
--| @relation s eq eq_refl eq_trans eq_sym _
axiom eq_refl (x: s): $ eq x x $;
axiom eq_trans (x y z: s): $ eq x y $ > $ eq y z $ > $ eq x z $;
axiom eq_sym (x y: s): $ eq x y $ > $ eq y x $;
--| @saturation horn
axiom p_from_q (x: s): $ q x $ > $ p x $;
"#;

#[test]
fn export_env_contains_stage_three_structures() {
    let env = parse_env(HORN_INPUT).unwrap();
    let export = ExportEnv::from_mm0(&env).unwrap();

    assert_eq!(export.sorts[0].egglog_name, "S");
    assert_eq!(export.relations["s"].relation, "eq");

    let p = export.term("p").unwrap();
    assert_eq!(p.kind, ExportTermKind::FactRelation);
    let eq = export.term("eq").unwrap();
    assert_eq!(eq.kind, ExportTermKind::RelationSymbol);

    assert_eq!(export.saturation_horn_rules.len(), 1);
    assert_eq!(export.saturation_horn_rules[0].rule_name, "p_from_q");
}

#[test]
fn generated_egglog_for_conversion_is_deterministic() {
    let env = parse_env(CONVERSION_INPUT).unwrap();
    let export = ExportEnv::from_mm0(&env).unwrap();
    let egglog = render_egglog(&export);

    let expected = concat!(
        ";; generated by eggbau; proof search is untrusted\n",
        ";; final MM0/MMB verification remains external\n",
        "\n",
        "(sort S)\n",
        "(sort Wff)\n",
        "\n",
        "(constructor Z () S)\n",
        "(constructor F (S) S)\n",
        "\n",
        "(ruleset saturation)\n",
        "\n",
        "(rule ((= eggbau_lhs (F v_x))) ((union eggbau_lhs v_x)) \
         :ruleset saturation :name \"f_id\")\n",
    );

    assert_eq!(egglog, expected);
    assert_eq!(render_egglog(&export), egglog);
}

#[test]
fn ltr_rtl_and_both_have_stable_rule_names_and_orientation() {
    let env = parse_env(
        r#"
sort s;
provable sort wff;
term z: s;
term f (x: s): s;
term eq (x y: s): wff;
--| @relation s eq eq_refl eq_trans eq_sym _
axiom eq_refl (x: s): $ eq x x $;
axiom eq_trans (x y z: s): $ eq x y $ > $ eq y z $ > $ eq x z $;
axiom eq_sym (x y: s): $ eq x y $ > $ eq y x $;
--| @saturation rtl
axiom rtl_law (x: s): $ eq (f x) x $;
--| @saturation both
axiom both_law (x: s): $ eq (f (f x)) (f x) $;
"#,
    )
    .unwrap();
    let export = ExportEnv::from_mm0(&env).unwrap();

    let rtl = &export.saturation_conversions[0].rules[0];
    assert_eq!(rtl.rule_name, "rtl_law");
    assert_eq!(rtl.direction, ConversionDirection::Rtl);
    assert!(rtl.needs_symmetry_for_mm0);

    let both = &export.saturation_conversions[1].rules;
    assert_eq!(both[0].rule_name, "both_law__sat_ltr");
    assert_eq!(both[1].rule_name, "both_law__sat_rtl");
    assert_eq!(export.saturation_conversions[1].mode, SaturationMode::Both);
}

#[test]
fn generated_program_derives_simple_conversion_goal() {
    let env = parse_env(CONVERSION_INPUT).unwrap();
    let export = ExportEnv::from_mm0(&env).unwrap();
    let program = render_egglog_with_schedule(&export)
        + "\n(F (Z))\n"
        + "(run-schedule (saturate (run saturation)))\n"
        + "(prove (= (F (Z)) (Z)))\n";

    run_egglog(&program);
}

#[test]
fn generated_program_derives_simple_horn_goal() {
    let env = parse_env(HORN_INPUT).unwrap();
    let export = ExportEnv::from_mm0(&env).unwrap();
    let program = render_egglog(&export)
        + "\n(q (Z))\n"
        + "(run-schedule (saturate (run saturation)))\n"
        + "(prove (p (Z)))\n";

    run_egglog(&program);
}

#[test]
fn rewrite_only_theorems_are_not_rendered_as_saturation_rules() {
    let env = parse_env(include_str!("fixtures/stage2/input.mm0")).unwrap();
    let export = ExportEnv::from_mm0(&env).unwrap();
    let egglog = render_egglog(&export);

    assert!(egglog.contains(":name \"annotated\""));
    assert!(!egglog.contains(":name \"rewrite_only\""));
}

#[test]
fn cli_script_emit_outputs_generated_program() {
    let output = Command::new(env!("CARGO_BIN_EXE_eggbau"))
        .args(["script", "emit", "tests/fixtures/stage2/input.mm0"])
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(output.stderr.is_empty());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("(ruleset saturation)"));
    assert!(stdout.contains(":name \"annotated\""));
}

fn run_egglog(program: &str) {
    let mut egraph = egglog::EGraph::new_with_proofs();
    let outputs = egraph
        .parse_and_run_program(None, program)
        .unwrap_or_else(|err| panic!("egglog failed:\n{err}\nprogram:\n{program}"));

    assert!(
        outputs
            .iter()
            .any(|output| { matches!(output, egglog::CommandOutput::ProveExists { .. }) })
    );
}
